apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels: 
    app: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - image: us-central1-docker.pkg.dev/mario-super-demo-496610/webapp/webapp:v2
        name: webapp
        ports:
        - containerPort: 5000
        
