apiVersion: v1
kind: Service
metadata:
  name: webapp-svc
  labels:
    app: webapp
spec:
  type: LoadBalancer
  ports:
    - name: webapp-svc
      port: 9000
      targetPort: 5000
  selector:
    app: webapp
