version: '3.8'
services:
  flask-app:
    build:
      context: ..
      dockerfile: Docker-Python/Dockerfile
    ports:
      - "9000:5000"
    environment:
      - DB_HOST
      - DB_NAME
      - DB_user
      - DB_pass
    restart: always
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${DB_user}
      - POSTGRES_PASSWORD=${DB_pass}
      - POSTDRES_DB=webapp
    volumes:
      - "../sqldata:/var/lib/postgresql/data"
    



